# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

matOmega1 <- function(W, rho) {
    .Call('saeRobust_matOmega1', PACKAGE = 'saeRobust', W, rho)
}

matOmega2 <- function(nTime, rho) {
    .Call('saeRobust_matOmega2', PACKAGE = 'saeRobust', nTime, rho)
}

matBlockDiagonal <- function(X, n) {
    .Call('saeRobust_matBlockDiagonal', PACKAGE = 'saeRobust', X, n)
}

matVInvT <- function(Ome1, sigma1, rho2, sigma2, Z1, sigmaSamplingError) {
    .Call('saeRobust_matVInvT', PACKAGE = 'saeRobust', Ome1, sigma1, rho2, sigma2, Z1, sigmaSamplingError)
}

matVDerS1 <- function(Ome1, Z1) {
    .Call('saeRobust_matVDerS1', PACKAGE = 'saeRobust', Ome1, Z1)
}

matVDerS2 <- function(Ome2, nDomains) {
    .Call('saeRobust_matVDerS2', PACKAGE = 'saeRobust', Ome2, nDomains)
}

matVDerR1 <- function(rho1, sigma1, Z1, Ome1, W) {
    .Call('saeRobust_matVDerR1', PACKAGE = 'saeRobust', rho1, sigma1, Z1, Ome1, W)
}

matVDerR2 <- function(rho2, sigma2, Ome2, nDomains) {
    .Call('saeRobust_matVDerR2', PACKAGE = 'saeRobust', rho2, sigma2, Ome2, nDomains)
}

fixedPointSigma <- function(y, X, beta, sigma, rho, Z1, Ome1, Z, sigmaSamplingError, k, K) {
    .Call('saeRobust_fixedPointSigma', PACKAGE = 'saeRobust', y, X, beta, sigma, rho, Z1, Ome1, Z, sigmaSamplingError, k, K)
}

